/*++
THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
PARTICULAR PURPOSE.
Copyright (c) 1995-1998  Microsoft Corporation

Module Name:  

hshell.h

Abstract:  

Interface to the Window Manager's Taskbar hooks. HSHELL_* are defined
in winuser.h


Notes: 


--*/
#ifndef _HSHELL_H_
#define _HSHELL_H_

#define WM_SHELLNOTIFY WM_USER

#endif /* HSHELL_H_ */
    
